defaults: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5
  template: template0
  collation: en_US.UTF-8
  ctype: en_US.UTF-8
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  database: <%= ENV['DATABASE'] || 'sql_tutor' %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *defaults

test:
  <<: *defaults
